<?php
/**
 * @file
 * Code for the GSB Feature Course CT feature.
 */

include_once 'gsb_feature_course_ct.features.inc';

/**
 * Implements hook_menu().
 */
function gsb_feature_course_ct_menu() {
  $items = array();
  $items['course-import/%'] = array(
    'title' => 'GSB course.',
    'description' => 'GSB course.',
    'page callback' => 'gsb_feature_course_ct_import_subject_all',
    'page arguments' => array(1),
    'access arguments' => array('administer nodes'),
  );   
  $items['admin/config/gsb/course-filters'] = array(
    'title' => 'GSB Course Filters',
    'description' => 'Set filters for Course import.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gsb_feature_course_ct_list_filters'),
    'access arguments' => array('access administration pages'),
  );
  $items['admin/config/gsb/course-filters/add'] = array(
    'title' => 'Add',
    'description' => 'Add filter for Courses import.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gsb_feature_course_ct_edit_filter'),
    'access arguments' => array('access administration pages'),
  );  
  $items['admin/config/gsb/course-filters/%/delete'] = array(
    'title' => 'Delete',
    'description' => 'Delete filter for Courses import.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gsb_feature_course_ct_delete_filter', 4),
    'access arguments' => array('access administration pages'),
  );   
  $items['admin/config/gsb/course-filters/%/edit'] = array(
    'title' => 'Edit',
    'description' => 'Edit filter for Courses import.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gsb_feature_course_ct_edit_filter', 4),
    'access arguments' => array('access administration pages'),
  );    
  return $items;
}

function gsb_feature_course_ct_cron()
{
   gsb_feature_course_ct_import_subject_all();
}

function gsb_feature_course_ct_import_subject_all($acad_year = NULL) {
 // $acad_year = '20122013';
  $subjects = array(
     'ACCT' => 'ACCT',
     'MGTECON' => 'MGTECON',
     'FINANCE' => 'FINANCE',
     'GSBGEN' => 'GSBGEN',
     'HRMGT' => 'HRMGT',
     'MKTG' => 'MKTG',
     'OIT' => 'OIT',
     'OB' => 'OB',
     'POLECON' => 'POLECON',
     'STRAMGT' => 'STRAMGT',
  );

    // Create feed importer content for each subject
  foreach ($subjects as $subject => $value) {
    gsb_feature_course_ct_import_course($acad_year, $subject);
  }

 return 'gsb_feature_course_ct_import completed';
}

function gsb_feature_course_ct_import_course($acad_year = NULL, $subject = 'ACCT') {

  $url = 'http://explorecourses.stanford.edu/search?view=xml-20130925&filter-coursestatus-Active=on&page=0&q='.$subject.'&academicYear='.$acad_year;
  $xml = simplexml_load_file(rawurlencode($url));

  if ($xml) {
    foreach ($xml->courses->course as $course) {
      // Check if the course exits by comparing year and courseID.
      gsb_feature_course_ct_course_import($course);
    }
  }
}

/*
 * Import courses
 */
function gsb_feature_course_ct_course_import($course) {

    $subject = (string)$course->subject;
    $code = (string)$course->code;

    // don't import any courses that are in the filter list

    $course_filters = variable_get('gsb_course_filters', array());

    if (!empty($course_filters[$subject])) {  
      if (in_array($code, $course_filters[$subject])) {
        return;
      }
    }
    if (!empty($course_filters['ALL'])) {
      if (in_array($code, $course_filters['ALL'])) {
        return;
      }
    }    

    // Split the year field
    $acad_year = explode('-', $course->year);
    $start_year = $acad_year[0]."-01-01";
    $start_date = new DateTime($start_year);

    $end_year = $acad_year[1]."-01-01";
    $end_date = new DateTime($end_year);

    // Check if the course already exists
    $query = new EntityFieldQuery();

    $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'course')
      ->fieldCondition('field_course_code', 'value', (string)$course->code)
      ->fieldCondition('field_course_subject', 'value', (string)$course->subject)             
      ->fieldCondition('field_course_start_acad_year', 'value', array($start_year))
      ->fieldCondition('field_course_end_acad_year', 'value', array($end_year));

    $entities = $query->execute();

    if (!empty($entities['node'])) {
      $nid = array_keys($entities['node']);
      $node = node_load(array_shift($nid));
     // echo 'Course updated';
    } else {
       $field_values = array(
          'type' => 'course',
          'uid' => 1,
          'status' => 1,
          'promote' => 0,
       );
       // Create the course
       $node = entity_create('node', $field_values);
    }
    // if the node isn't a course
    if ($node->type != 'course') {
      return;
    }

    // updatet the course node information
    $wrapper = entity_metadata_wrapper('node', $node);
    $wrapper->title->set((string)$course->title);

    $wrapper->field_course_id->set((string)$course->administrativeInformation->courseId);
    $wrapper->field_course_subject->set((string)$course->subject);
    $wrapper->field_course_code->set((string)$course->code);
    $wrapper->field_course_start_acad_year->set($start_date->getTimestamp());
    $wrapper->field_course_end_acad_year->set($end_date->getTimestamp());
    $wrapper->field_body = array(
       'value' => $course->description,
       'format' => 'full_html',
    );
    //$wrapper->field_body->set((string)$course->description); // description input needs to fixed

    $xml_sections = $course->sections;
    $entity_ids = array();

    // update the faculty node id by sunet
    foreach ($xml_sections->section as $section) {

      // update the entity reference for sunet
      if (!empty($section->schedules->schedule->instructors->instructor->sunet)
          && trim($section->schedules->schedule->instructors->instructor->sunet) != '') {

        if (count($section->schedules->schedule->instructors->instructor) > 1) {
          foreach($section->schedules->schedule->instructors->instructor as $instructor) {
            $sunet_id = $instructor->sunet;
            $entity_ids = array_replace(_gsb_feature_course_ct_add_faculty($sunet_id), $entity_ids);
          }
        }
        else {
          $sunet_id = $section->schedules->schedule->instructors->instructor->sunet;
          $entity_ids = array_replace(_gsb_feature_course_ct_add_faculty($sunet_id), $entity_ids);
        }
        
      }
    }

    if (!empty($entity_ids)) {
      $wrapper->field_person_fac_ref->set($entity_ids);
    }
    else {
      $wrapper->field_person_fac_ref->set(NULL);
    }

    // Finally save the entity
    $wrapper->save();
}

function _gsb_feature_course_ct_add_faculty($sunet_id) {

  $entity_ids = array();

  // try to locate the sunet from faculty content
  $entity_id = db_select('field_data_field_sunetid', 'su')
    ->fields('su', array('entity_id'))
    ->condition('su.field_sunetid_value',$sunet_id)
    ->condition('su.bundle','faculty')
    ->execute()->fetchField();

  if ($entity_id && !in_array($entity_id, $entity_ids)) {
    $entity_ids[$entity_id] = $entity_id;
  }

  return $entity_ids;
}

////////////////////////////////////////////////////////////////////////
// Functions related to Course Filtering 

function gsb_feature_course_ct_list_filters($form, &$form_state) {

  $form['addlink'] = array(
    '#type' => 'link',
    '#title' => t('Add filter'),
    '#href' => 'admin/config/gsb/course-filters/add',
  );

  $course_filters = variable_get('gsb_course_ct_filters', array());

  if (!empty($course_filters)) {

    $rows = array();

    ksort($course_filters);
    _gsb_feature_course_ct_move_all_first($course_filters);

    foreach ($course_filters as $key => $codes) {

      sort($codes);

      foreach($codes as $code) {

        $row = array();

        $row['data'][] = $key;
        $row['data'][] = $code;

        $operations = array();
        $operations['edit'] = array(
          'title' => t('Edit'),
          'href' => 'admin/config/gsb/course-filters/' . $key .'-' . $code . '/edit',
        );
        $operations['delete'] = array(
          'title' => t('Delete'),
          'href' => 'admin/config/gsb/course-filters/' . $key .'-' . $code . '/delete',
        );
        $row['data']['operations'] = array(
          'data' => array(
            '#theme' => 'links',
            '#links' => $operations,
            '#attributes' => array('class' => array('links', 'inline')),
          ),
        );  

        $rows[$key .'-'.$code] = $row;

      }

    }

    $form['table'] = array(
      '#theme' => 'table',
      '#header' => array(
        t('Course Subject'),
        t('Course Code'),
        t('Operations'),
      ),
      '#rows' => $rows,
    );  

  }

  return $form; 
}

/**
 * Edit the Course Filter.
 */
function gsb_feature_course_ct_edit_filter($form, $form_state, $subject_code = null) {

  $subject = null;
  $code = null;
  if ($subject_code != null) {
    list($subject, $code) = explode('-',$subject_code);    
  }

  $form = _gsb_feature_course_ct_get_basic_form();

  if ($subject != null) {
    $form['course_subject']['#default_value'] = $subject;
    $form['course_subject']['#disabled'] = TRUE;      
  }
  
  if ($code != null) {
    $form['course_code']['#default_value'] = $code;    
  }

  $form['#submit'][] = 'gsb_feature_course_ct_edit_filter_submit';    

  return system_settings_form($form, $form_state);
}  

/**
 * Save the Course Filter.
 */
function gsb_feature_course_ct_edit_filter_submit($form, &$form_state) {

  $subject = $form_state['values']['course_subject'];
  $code = $form_state['values']['course_code'];

  if (!empty($form_state['build_info']['args'])) {
    // get the subject and previous code
    $subject_code = $form_state['build_info']['args'][0];
    list($subject, $old_code) = explode('-',$subject_code);
    // delete the old code
    _gsb_feature_course_ct_delete_filter_code($subject, $old_code);
  }

  // add the new code
  _gsb_feature_course_ct_add_filter_code($subject, $code);

  $form_state['redirect'] = array('admin/config/gsb/course-filters');

}

/**
 * Delete the Course Filter.
 */
function gsb_feature_course_ct_delete_filter($form, $form_state, $subject_code) {

  $question = t('Are you sure you want to delete this filter?');
  $destination = 'admin/config/gsb/course-filters';

  return confirm_form($form, NULL, $destination, $question, t('Delete'), t('Cancel'));
}  

function gsb_feature_course_ct_delete_filter_submit($form, &$form_state) {

  $subject_code = $form_state['build_info']['args'][0];
  list($subject, $code) = explode('-',$subject_code);

  _gsb_feature_course_ct_delete_filter_code($subject, $code);

  $form_state['redirect'] = array('admin/config/gsb/course-filters');

}  

function _gsb_feature_course_ct_add_filter_code($subject, $code) {

  $course_filters = variable_get('gsb_course_ct_filters', array());

  if(!empty($course_filters[$subject])) {
    $course_filters[$subject] = array_unique (array_merge($course_filters[$subject], array($code)));
  }
  else {
    $course_filters[$subject] = array($code);
  }

  variable_set('gsb_course_ct_filters', $course_filters);
}

function _gsb_feature_course_ct_delete_filter_code($subject, $code) {

  $course_filters = variable_get('gsb_course_ct_filters', array());

  if (!empty($course_filters[$subject])) {
    $codes = $course_filters[$subject];
    foreach($course_filters[$subject] as $key => $value) {
      if ($value == $code) {
        unset($codes[$key]);
        break;
      }    
    }  
    $course_filters[$subject] = $codes;
  }

  variable_set('gsb_course_ct_filters', $course_filters);
}  

function _gsb_feature_course_ct_get_basic_form() {

  $form = array();

  $subjects = array(
    'ALL' => 'All',
    'ACCT' => 'ACCT',
    'FINANCE' => 'FINANCE',
    'GSBGEN' => 'GSBGEN',
    'HRMGT' => 'HRMGT',
    'MGTECON' => 'MGTECON',    
    'MKTG' => 'MKTG',
    'OB' => 'OB',    
    'OIT' => 'OIT',
    'POLECON' => 'POLECON',
    'STRAMGT' => 'STRAMGT',
  );  

  $form['course_subject'] = array(
    '#type' => 'select',
    '#title' => t('Select Course Subject'),
    '#options' => $subjects,
    '#description' => t('Select which course subject that will be used in the filter.')
  );  

  $form['course_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Course Code'),
    '#required' => TRUE,
    '#description' => t('Set the course code that will be used in the filter.')
  );    

  return $form;
}  

function _gsb_feature_course_ct_move_all_first(&$course_filters) {

  // We move the items marked with the 'all' subject to the top 
  // of the listed items, since these have global impact and 
  // therefore have more importance

  if (!empty($course_filters['ALL'])) {
    $all = $course_filters['ALL'];
    unset($course_filters['ALL']);
    $temp = array();
    $temp['ALL'] = $all;
    $course_filters = $temp + $course_filters;
  } 

}


